.PHONY: default clean

CC=gcc
CFLAGS=-Wall -Wextra -std=c99 -g

default: bheap hashmap rlist hlist
bheap: bheap.c
hashmap: hashmap.c
rlist: rlist.c
hlist: hlist.c
clean:
	rm -f bheap hashmap rlist hlist
